### ISSUE TITLE
High resolution is quite buggy

### ISSUE THREAD

**Issue by Jacktherookie** [AIRLegend/aitrack#100]
**Describe the bug**
When I'm trying to change resolution to FHD (1920x1080) in Settings, it really buggy.

**To Reproduce**
1. Go to Settings
2. Change resolution to FHD (1920x1080)
3. See error

**Expected behavior**

Camera fps drop down to like 2 fps

**Screenshots**

**Environment (please complete the following information):**
 - Operating system version (Windows 10+ Version number): 
 - Webcam model: 
 - AITrack version:

**Additional context**

**Comment by AIRLegend** [comment]
Most cameras reduce their FPS on low-light settings. Could that be your case?

If your camera supports a lower resolution you should use it because a higher one will only eat more CPU. Internally, the program downscales the video feed either way.

**Comment by Jacktherookie** [comment]
I dont think low light is a problem for me. I'm pretty sure I have decent light for my webcam. But I did reset my PC and It work smoothly. I think something in my PC was hindering Track.
