### ISSUE TITLE
Windows defender seeing AItrack as trojan

### ISSUE THREAD

**Issue by RyanEhrlich** [AIRLegend/aitrack#126]
When running aitrack windows defender tags this "file: C:\Program Files (x86)\opentrack\modules\opentrack-tracker-freepie-udp.dll" as veing affected by Trojan:Script/Phonzy.A!ml

**Comment by AIRLegend** [comment]
Hi!

That's part of the Opentrack program. Maybe you could whitelist it. If the problem persists, I think it's better you post it on [their issues page](https://github.com/opentrack/opentrack/issues).

Have a nice day :)
