### ISSUE TITLE
PS3 Eye Blackscreen

### ISSUE THREAD

**Issue by Everexx** [AIRLegend/aitrack#138]
PS3 Eye cam shows blackscreen in AItrack
CL-Eye test works fine.

**Comment by AIRLegend** [comment]
Hello. Make sure the resolution and fps you set within the config window are compatible with the camera.

**Comment by searching46dof** [comment]
When I had the wrong resolution/fps the application did not respond.
You may want to check the gain/exposure and amount of lighting and that another app does not have ownership of the camera device.
