### ISSUE TITLE
doesn't work on Windows11?

### ISSUE THREAD

**Issue by Lnsynd** [AIRLegend/aitrack#139]
1.Click on 'AITrack.exe'
2.can't work

**Comment by ScottESanDiego** [comment]
Not sure that's enough steps to reproduce. :-) FWIW, works great on Windows 11 for myself, and many others.

What does "can't work" mean?

**Comment by Pollot** [comment]
It works on Windows 11 just fine (21H2 as well as 22H2)

**Comment by CMDRTreya** [comment]
No clue if this is the same problem that @Lnsynd encountered but apparently AITrack needs write access to its folder. I had extracted the folder to "C:\Program files" and from there AITrack would only run with admin privileges. Moving the folder somewhere else (with write access) solved that.
