### ISSUE TITLE
Missing a lot of QT5 libary

### ISSUE THREAD

**Issue by nhatmicls** [AIRLegend/aitrack#146]
I just download and run it, I show a lot of missing QT5_xxx.dll. After I downloaded missing dll it show me missing ```opencv_world430.dll``` and I can't find it in google (It have some opencv_worldxxx.dll but not same version).

1. Run
2. And get error

Screenshots
![image](https://user-images.githubusercontent.com/20109101/175899148-cdb4458b-5095-474e-85ed-e1509cdc04ac.png)
![image](https://user-images.githubusercontent.com/20109101/175899963-cf0017db-dd1a-4c40-b72e-91f6247ef026.png)

Type of missing:
- Qt5Core.dll
- Qt5Gui.dll
- Qt5Network.dll
- Qt5Widgets.dll
- opencv_world430.dll

Environment (please complete the following information):
 - Operating system version (Windows 10+ Version number): 21H2
 - Webcam model: Rapoo C280/DroidCam
 - AITrack version: v.0.6.5

**Comment by AIRLegend** [comment]
Please, check again as those files are inside the release zip. Maybe your AV has deleted them.
