### ISSUE TITLE
Screenshots of opentrack configuration for using aitrack in a flight simulator or driving game

### ISSUE THREAD

**Issue by searching46dof** [AIRLegend/aitrack#154]
**Describe your idea**
A clear and concise description of what the idea. Ex. I'm always frustrated when [...]

Screenshots of opentrack configuration for using aitrack in a flight simulator or driving game.
A picture is worth a thousand words and it would make it much easier to set up.

**Describe the solution you'd like**

Provide a link from the readme to a section of the wiki containing the pictures.

**Describe alternatives you've considered**

Providing a sample opentrack configuration but the format of opentrack configuration may change.

**Additional context**
![01 opentrack UDP_over_network input](https://user-images.githubusercontent.com/107732149/182513216-c4d71e72-48b2-4585-a7b8-9bfa198aa462.jpg)
![02 opentrack HamiltonFilter](https://user-images.githubusercontent.com/107732149/182513220-229fc329-a538-4a3e-a607-8891cf2e545f.jpg)
![03 opentrack options center_at_startup](https://user-images.githubusercontent.com/107732149/182513222-6287ca3d-17b6-467a-b99d-e33f5b1cd33b.jpg)
![04 opentrack options output_remap](https://user-images.githubusercontent.com/107732149/182513226-74b88671-0cd2-447e-91ab-8785f4666bee.jpg)
![05 opentrack mapping_properties yaw](https://user-images.githubusercontent.com/107732149/182513228-29d2057b-9112-42cc-80dd-793dcbd761cb.jpg)
![06 opentrack mapping_properties pitch](https://user-images.githubusercontent.com/107732149/182513231-b3074f3a-d762-4625-9cbe-660a7f5b3355.jpg)
![07 opentrack mapping_properties roll](https://user-images.githubusercontent.com/107732149/182513236-19a45c80-5b13-42f4-b1d5-b4b8f00f665a.jpg)
![08 opentrack mapping_properties x](https://user-images.githubusercontent.com/107732149/182513238-855f4c73-bf6c-4274-b88e-8d24e2640eb9.jpg)
![09 opentrack mapping_properties y](https://user-images.githubusercontent.com/107732149/182513240-8d59967e-4171-42c5-93a1-f5d0d10c535a.jpg)
![10 opentrack mapping_properties z](https://user-images.githubusercontent.com/107732149/182513242-c8ee352f-27ec-410b-98e5-5c1f434b77d4.jpg)

Some additional notes:
- Use same port for opentrack and aitrack.
- Look at center of monitor when starting aitrack and opentrack with center at startup option.
- Yaw scales raw 30degrees to 120degrees equivalent to looking over shoulder
- Pitch scales raw 30degrees to 90degrees equivalent to looking up and down.
- X and Y mapping are disabled to be always centered as if strapped into chair.
- Z mapping to look closer at instrument panel.

For more realism:
- The Z mapping may also be applied to the X and Y to look around virtual joystick, yoke or steering wheel or provide different view in mirrors.
- Remove or minimize the center null zone but this may add jitter and make it more difficult to read instruments.

**Comment by AIRLegend** [comment]
Just included this in the [User guide](https://github.com/AIRLegend/aitrack/wiki/User-guide).

Thank you!!
