### ISSUE TITLE
Detect camera resolutions

### ISSUE THREAD

**Issue by AIRLegend** [AIRLegend/aitrack#16]
Right now, the default resolution for a generic camera is set to 640x480. Thanks to @rbroker, the ability to change the resolution via `prefs.ini` is possible. However, an automatic approach is needed. 

A system to check all the available camera resolutions should be implemented and called inside CameraFactory.cpp (https://github.com/AIRLegend/aitrack/blob/master/Client/src/camera/CameraFactory.cpp) in order to create an OCVCamera (https://github.com/AIRLegend/aitrack/blob/master/Client/src/camera/OCVCamera.h) with the lowest resolution compatible.

**Comment by AIRLegend** [comment]
That seems a nicer solution. I will implement it and see how much it increases CPU usage. Cheers!

**Comment by AIRLegend** [comment]
Already added this in the new release. Could you please check it doesn't crash anymore?

**Comment by rbroker** [comment]
> Could you please check it doesn't crash anymore?

Just tried it, working like a charm, no crash 👍  Thanks for sharing this!

**Comment by AIRLegend** [comment]
Great! Closing then :)
