### ISSUE TITLE
The Ability to use OBS Virtual Camera

### ISSUE THREAD

**Issue by azrialtide** [AIRLegend/aitrack#197]
**Describe your idea**
I'm always in a discord call with my webcam so I tried to use OBS virtual camera and it doesn't even detect in the camera list

**Describe the solution you'd like**
Allow the use of Virtual Cameras

**Comment by azrialtide** [comment]
found out you can use SplitCam instead and it works correctly

**Comment by AIRLegend** [comment]
Actually, some people use it with OBS virtual cams (although I never tried).

Marking as solved :)
