### ISSUE TITLE
Can't find the .exe file

### ISSUE THREAD

**Issue by czross** [AIRLegend/aitrack#207]
**Describe the bug**
I might be having a dumb moment, but I cannot for the life of me find where the .exe file is either in the GitHub repo or on my personal copy. 

**To Reproduce**
download files and try and find the dang .exe file.

**Expected behavior**

**Screenshots**
![ai-track-exe](https://user-images.githubusercontent.com/13024912/218372409-fffabab5-442b-4e12-8d5b-b8d41cce0758.PNG)

**Environment (please complete the following information):**
 - Operating system version (Windows 10+ Version number): 
 - Webcam model: 
 - AITrack version:

**Additional context**

**Comment by searching46dof** [comment]
on the main webpage, click on releases on the right side.
then click on a specific release e.g. 0.71 which will provide a link for downloading that release archive

**Comment by czross** [comment]
Yup just me being a goober, thanks!
