### ISSUE TITLE
How to decrease latency?

### ISSUE THREAD

**Issue by BaldiosY** [AIRLegend/aitrack#211]
**Describe the bug**

**To Reproduce**

**Expected behavior**
I installed AITrack and was quite impressed with how it works, a friend recommended it to me. Using the DCS simulator, after a quick setup, I have noticed that there is some latency during head movements. How can I reduce it further?

**Screenshots**

**Environment (please complete the following information):**
 - Operating system version (Windows 10+ Version number): Ultimate build Win 10 
 - Webcam model:  Mediacom M455 30fps FullHD 1080
 - AITrack version: 0.7.1 

**Additional context**
In ConfigWindow of AITrack in the camera section the resolution is set to 640x480 with 30 FPS

**Comment by RedSnt** [comment]
Have you tried other opentrack filters or setting up the default one? It's one of the FAQ questions and refers to[ this article](https://github.com/opentrack/opentrack/wiki/Accela-in-opentrack-2.3) on how to set smoothing and so on.

**Comment by BaldiosY** [comment]
Thank you for your answer. In rotation filtering I set a maximum of 0.1° in the deadzone, while in Position filtering how much should I set it? The benchmark is in millimeters...

**Comment by BaldiosY** [comment]
I fixed it by increasing the FPS in the AITrack settings to 120.

**Comment by BaldiosY** [comment]
I fixed it by increasing the FPS in the AITrack settings to 120.
