### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [AIRLegend/aitrack#28]
Would you like to [wrap any pointer data members](https://github.com/AIRLegend/aitrack/blob/9e455e10990969a157cbd1c066f90eede60d6ee3/AITracker/src/model.cpp#L11 "Update candidate: Tracker class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by AIRLegend** [comment]
I don't think it's worth the effort on that class. The only public member which is worth of checking not `nullptr` is `PositionSolver`. Maybe a shared_ptr or a getter/setter for updating it and rising an exception in case of wrong set. However, I think it's better to delegate that on the caller (aka. TrackerWrapper and TrackerFactory).

**Comment by rbroker** [comment]
I don't mind taking a look at the client part.

**Comment by elfring** [comment]
How do you think about to integrate any evolving software development approaches?

**Comment by AIRLegend** [comment]
What do you specifically mean? @elfring

**Comment by elfring** [comment]
@rbroker published a software development approach which looks promising.
