### ISSUE TITLE
Crash after tracking start

### ISSUE THREAD

**Issue by meznak** [AIRLegend/aitrack#35]
**Describe the bug**
Crash when starting tracking

**To Reproduce**
1. Fresh copy of v0.6
2. Click on 'Configuration'
3. Select camera from dropdown
4. Click 'Apply'
5. Click 'Start Tracking'
6. Look around a bit
7. App crashes with no message

**Expected behavior**
App tracks properly without crashing

**Environment (please complete the following information):**
 - Win 10 Home x64 v1909 build 18363.1016
 - Webcam model: Logitech c260 (also active: LarmTek 1080p full HD)
 - AITrack version: 0.6

**Additional context**
Using with OpenTrack 2.3.12

**Comment by AIRLegend** [comment]
Did you have the same issue while using 0.5.1?

**Comment by n9533** [comment]
I'm having the same issue with 0.6 and 0.5.1

**Comment by AIRLegend** [comment]
I've just released version 0.6.1 which adds a logging system. It could help us in figuring out what's happening. 
Please, post the content of `log.txt` here.

**Comment by AIRLegend** [comment]
As commented on Discord, manually setting FPS=30 for your camera in the cofiguration window seems to fix the issue.

**Comment by egovice** [comment]
> As commented on Discord, manually setting FPS=30 for your camera in the cofiguration window seems to fix the issue.

I found any positive number fixed it in my case; although an FPS of 1 isn't exactly usuable

**Comment by meznak** [comment]
Not crashing in 0.6.1 after manually setting FPS.

**Comment by Chaya56** [comment]
+1, by default FPS is 0 and it make crash app, setting it to another value make it work

**Comment by AIRLegend** [comment]
Glad to hear that! The fix will be included with the new release. 
Closing.
