### ISSUE TITLE
Option to use CL-Eye driver or built in PS3 driver.

### ISSUE THREAD

**Issue by pixelbreaker** [AIRLegend/aitrack#41]
Would it be possible to have a choice which PS3 driver is used (CL eye already installed or your internal PS3 driver)?

I'm finding the driver you force is bad in low light even with exposure/gain raised a lot, and the landmarks even with stabilization are really twitchy.

**Comment by AIRLegend** [comment]
The built-in driver searches for Directshow cameras available in Windows, so it seems you need a driver installed (CL Eye or WinUSB). 

With the PS3 camera you can configure brightness/exposure in the Options menu. Just drag the sliders to override its default value.
