### ISSUE TITLE
Compensate camera position offset. ("report" movement relative to screen, not camera)

### ISSUE THREAD

**Issue by yanghu** [AIRLegend/aitrack#42]
**Describe your idea**
I'm always frustrated when moving in Z direction, or yaw left/right. Since the camera is mounted at the top of the screen, there's an offset: if I'm moving directly to the screen, instead of a +Z movement, the camera would detect a -Y.(very strong when moving close the the camera). This totally breaks the immersion.

Same when I look left/right. Since the camera is looking down at me, the left/right look would always induce a pitch movement. Instead of looking left/right in game, it would look left+down, or right+down. 

In short: the current implementation reports the 6DOF movement relative to the CAMERA, not the MONITOR.(where our focus is at)

**Describe the solution you'd like**
Theoretically, we should be able to easily compensate for the camera's offset from the screen center, and calculate the 6DOF data relative to the screen center.
We may ask users to input their horizontal/vertical offset to the camera. 
Currently we assume/require users to put camera at nose height. However that's really hard/impossible: there's the monitor at that place.

**Describe alternatives you've considered**
It's almost impossible to put camera at the center of the screen, so no very good way.

**Additional context**
I did tried other algorithms/apps for face tracking and some did pretty well on this. I simply my my head towards the screen, and the virtual camera would pan forward. Although I'm not moving towards the tracking camera.

**Comment by AIRLegend** [comment]
Cancelled this induced rotation in #51. Hope it's better now :)

Closing this idea thread.
