### ISSUE TITLE
Video capture broken - seems as if multiple streams are combined horizontally and fed into tracking

### ISSUE THREAD

**Issue by skalteis** [AIRLegend/aitrack#47]
**Describe the bug**
Video capture broken - seems as if multiple streams are combined horizontally and fed into tracking

**To Reproduce**
Open webcam at native resolution and frame rate - get three video streams combined horizontally which are fed into the tracker.

**Expected behavior**
One video stream at the set dimension and frame rate

**Screenshots**
![aitrackbug](https://user-images.githubusercontent.com/4951046/92328996-ddfd9200-f064-11ea-8458-8a36fe98ca41.PNG)

**Environment (please complete the following information):**
 - Windows 10 build 19041
 - Webcam model: Kurokesu C1PRO (Sony IMX291, UVC USB class compliant)
 - AITrack version: 0.6.1-alpha

Thank you very much for this awesome program! :-)

**Comment by AIRLegend** [comment]
This has been fixed in#51 and already available in v0.6.2 :)
