### ISSUE TITLE
Crash if selected camera is unplugged

### ISSUE THREAD

**Issue by LiftPizzas** [AIRLegend/aitrack#53]
On loading, it looks for camera index "selected_camera=" from prefs.ini. If that camera doesn't exist it just exits with no message.

**To Reproduce**
1- plug in two webcams.
B. Run aitrack and select the second camera.
3. Exit out to desktop.
4. Unplug the second camera.
E. Launch again, observe crash.

**Expected behavior**
Should gracefully handle a missing camera. If the selected one is not found, do something like reset index to 0 and use a messagebox to inform user of the situation.

**Environment (please complete the following information):**
 - Windows 10 2004
 - Webcam model: will happen with any model
 - AITrack version: 0.6.1

**Comment by 1234filip** [comment]
+1 on this
