### ISSUE TITLE
The code execution cannot proceed because VCRUNTIME140_1.dll was not found. reinstalling the program may fix this problem. Tried reinstalling the dll from MS and re-downloaded the aitrack app.

### ISSUE THREAD

**Issue by in10sive1** [AIRLegend/aitrack#56]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Operating system version (Windows 10+ Version number): 
 - Webcam model: 
 - AITrack version:

**Additional context**

**Comment by AIRLegend** [comment]
Install the [Visual c++ redistributable](https://aka.ms/vs/16/release/vc_redist.x64.exe) package.
