### ISSUE TITLE
Random glitches when keeping head steady

### ISSUE THREAD

**Issue by karoletrych** [AIRLegend/aitrack#57]
All of the values seem to change rapidly at random moments when I keep head steady.

**Screenshots**
https://www.youtube.com/watch?v=k6IYNwVJtt8
https://www.youtube.com/watch?v=jvwk6xHQHmM

**Environment (please complete the following information):**
 - Operating system version: Windows 10 Version 2004
 - Webcam model: Logitech C270
 - AITrack version: 0.6.2

**Additional context**
Seems to me like an autofocus problem, but from what I see the C270 doesn't have it.

**Comment by AIRLegend** [comment]
Thanks for the videos! 
Seems to be the same that #49, so I'll close this and continue updating there. I would appreciate you commenting those two videos there :)

As a quick update, I think this issue could be already fixed but still needs a proper implementation for the next update (I will do it as soon as I can).
