### ISSUE TITLE
Tracking with headset on

### ISSUE THREAD

**Issue by Xebozone** [AIRLegend/aitrack#68]
Thanks for all your hard work. I love the app!

**Describe your idea**
The app doesn't work too great with a headset on (Phone VR with Riftcat using Freetrack tracking)
I suppose it looks for the eyes which cannot be seen with a headset on.

**Describe the solution you'd like**
Rely just on head shape/mouth tracking, or add the ability for manual tracking points

**Describe alternatives you've considered**
I could stick some printed eyes on the headset, but that's creepy 🤣 

**Additional context**
Thanks!

**Comment by Xebozone** [comment]
This looks cool which may be a useful library FYI:
https://github.com/google/mediapipe

Found it while reading this project:
https://github.com/ChristophGeske/ARCoreInsideOutTrackingGearVr

**Comment by AIRLegend** [comment]
Thanks for the idea! I actually tried MediaPipe's models but found that they  are extremely noisy for this (as they're intended for their use on mobile phones). 
On the other hand, support for VR headsets is not on the near roadmap, sorry!
