### ISSUE TITLE
Error on windows 10

### ISSUE THREAD

**Issue by marcelcandidoferreira** [AIRLegend/aitrack#70]
**Describe the bug**
I'm trying to open it in windows 10, but receiving the error bellow
![image](https://user-images.githubusercontent.com/15752746/97083231-9dd67c80-15dc-11eb-8da8-fe91a11a026a.png)

**To Reproduce**
1. Open droidcam client and connect to webcam
2. Open OpenTrackAi and select input UDP Over Network, then click in Start
3. Try to open AiTrack and get the error

**Environment (please complete the following information):**
 - Operating system version (Windows 10+ Version number):  Windows 10  Version	10.0.19041 Build 19041
 - Webcam model: DroidCam
 - AITrack version:  aitrack-v0.6.3-alpha

**Comment by AIRLegend** [comment]
Are you executing an AITrack.exe  which is next to all the required QT dll's? (Included within the .zip)

**Comment by peter74-sys** [comment]
problem here
aitrack.exe will not run on windows 10
downloaded v0.6.3 alpha and tried older ones
get blank page and then stop working

**Comment by AIRLegend** [comment]
@peter74-sys Your problem should be solved on v0.6.4

Closing the issue because of inactivity.
