### ISSUE TITLE
Camera FOV update for Logitech c270

### ISSUE THREAD

**Issue by gannon345** [AIRLegend/aitrack#71]
Apologies for putting this in the issue/feature tracker. I would have made the update myself but I didn't see a link where I could edit the wiki on the page.

For the [common camera FOV settings](https://github.com/AIRLegend/aitrack/wiki/Common-camera-FOV-values#common-camera-fovs-field-of-view-degrees) page, the Logitech c270 has a FOV of 60. 

It's not a great camera by any means, but it's worked well for me at 640x480 with aitrack. Good budget option if anyone wants to get started with aitrack.

Thanks for the amazing app.

**Comment by AIRLegend** [comment]
Oh, sorry. I thought it was editable. It should be changed now :)

Already added! Thanks for reporting!
