### ISSUE TITLE
ERRORE DI SISTEMA

### ISSUE THREAD

**Issue by FMatteo87** [AIRLegend/aitrack#72]
errore di sistema Su windows 10 

"l esecuzione del codice non puo proseguire perche MSVCP140.dll non e stato trovato. Per risolvere il problema prova a reinstallare il programma" seguono altri 3 errori con la stessa dicitura ma diversi DLL
VCOMP140.DLL
VCRUNTIME140_1.dll
VCRUNTIME140.dll

**Comment by AIRLegend** [comment]
Seems you don't have Visual C++ Redistributable installed. Please, follow this steps: https://github.com/AIRLegend/aitrack#installing-and-running
