### ISSUE TITLE
Preview screen split vertically on startup.

### ISSUE THREAD

**Issue by jrettew** [AIRLegend/aitrack#74]
Almost but not quite every time I start the preview, the screen is split vertically as in the attached screen shot.  

![aitrack split screen](https://user-images.githubusercontent.com/73974482/98187530-23143800-1edf-11eb-8354-ddf1426d28df.jpg)

**Comment by AIRLegend** [comment]
Hi!
Please, make sure the camera parameters in AITrack are correctly matching your camera's capabilities (both resolution and FPS). 
Also, changing your camera to another USB port could help (and avoiding using USB Hubs to connect it to the computer).

**Comment by jrettew** [comment]
I will do that. Thank you!

John

**Comment by jrettew** [comment]
It was the resolution.  Thanks again!
