### ISSUE TITLE
Dropping frames at higher resolutions

### ISSUE THREAD

**Issue by 1234filip** [AIRLegend/aitrack#76]
**Describe the bug**
The software slows way down on higher resolutions.

**To Reproduce**
Works really well on 640x480.
When I try to bump it up to 1280x720 it introduces high latency and starts dropping frames.

 - Webcam model: Some generic Full HD webcam.
 - AITrack version: 0.6.3

**Additional context**
The CPU usage doesn't even max out, stays at about 10%. Also checked the cores, no core is maxed out. Memory usage seems to stay the same. I have a pretty good PC so running a face detection model shouldn't too hard for it. I think there a problem with loading higher resolution frames as the Fast/Heavy model difference in performance is non-noticable.

**Comment by AIRLegend** [comment]
Maybe the problem is on the camera. 720p have been pretty tested and it seems to be okay. Could you have other process running and interfering with the capture?

**Comment by 1234filip** [comment]
It was a weird bug with the drivers of my camera. Fixed now.
