### ISSUE TITLE
FOV settings reverts after closing the window

### ISSUE THREAD

**Issue by gannon345** [AIRLegend/aitrack#77]
**Describe the bug**
On my Logitech c270, FOV is defaulted to 56. Actual FOV should be 60, but after changing the value and saving, when you close and reopen the configuration panel, it's 56 again

**To Reproduce**
1. Click "configuration"
2. change camera FOV value
3. Save and close configuration
4. reopen configuration

**Expected behavior**
FOV value stays at the value set

**Screenshots**
N/A
**Environment (please complete the following information):**
 - Windows 10
 - Webcam model: Logitech c270
 - AITrack version: 0.6.3

**Additional context**
N/A

**Comment by AIRLegend** [comment]
I'm aware of the bug. It's already fixed on the develop branch and it will be solved with the next update. In the meantime, you can edit the value inside `prefs.ini` file.

Sorry for the inconvenience and thanks for reporting!
