### ISSUE TITLE
CTRL+T Shortcut options

### ISSUE THREAD

**Issue by Dymerz** [AIRLegend/aitrack#92]
**Describe your idea**
Add an option to enable/disable the CTRL+T shortcut, I'm always frustrated when I want to open a new tab (CTRL+T) in my web explorer and AITrack catch the event, so my new tab isn't opened.

**Describe the solution you'd like**
An option to enable/disable the CTRL+T shortcut.

**Describe alternatives you've considered**
Click on the "+" icon of the web explorer or close AITrack.

**Comment by gabrielbunselmeyer** [comment]
+1 to this idea. It's pretty annoying currently 😬

**Comment by UNDEFINED-BEHAVIOR** [comment]
Hello
Recently it's been annoying enough that I've implemented shortcuts toggling myself. It's "works on my machine" status right now but if you don't mind I could arrange a pull request perhaps.
![aitrack with shortcut toggle](https://user-images.githubusercontent.com/8407331/128639664-5d29f25d-b019-445e-a6e4-520ff8181616.jpg)

**Comment by AIRLegend** [comment]
Hey @UNDEFINED-BEHAVIOR, cool! Glad to merge it if you don't mind making the PR :). 

Could you move it into the configuration menu though? The main view should be as clean as possible.

**Comment by UNDEFINED-BEHAVIOR** [comment]
I'll think about it, will just make the PR as is first.
If it's in config menu then it should also go in to pref.ini

**Comment by UNDEFINED-BEHAVIOR** [comment]
![image](https://user-images.githubusercontent.com/8407331/128668056-f59f93da-d26f-4c90-90c6-555dc5871d0e.png)
Ok its been moved to config window, and should be saved in pref file now.

**Comment by AIRLegend** [comment]
Ok, this is merged and it will be available with the next version :) Thank you very much @UNDEFINED-BEHAVIOR!

For those who want this right now, you have the compiled program here (Hope you can access it): https://ci.appveyor.com/project/AIRLegend/aitrack/builds/40302101/artifacts

Closing. Have a nice day :)
