### ISSUE TITLE
help something is missing 

### ISSUE THREAD

**Issue by darkice1983** [AIRLegend/aitrack#97]
hi i am trying to run AIrLegend and keep getting this message 
<a href="https://www.linkpicture.com/view.php?img=LPic607f4318994af373363547"><img src="https://www.linkpicture.com/q/Untitled_60.png" type="image"></a>

**Comment by AIRLegend** [comment]
You should install the C++ redistributable. The guide it's on the [Wiki](https://github.com/AIRLegend/aitrack/wiki/User-guide)
